seed_everything: 2234
trainer:
  max_epochs: 1000
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: '.'
      name: 'logs/VAE_MNIST/fit_logs'
      default_hp_metric: False
  callbacks:
    - class_path: ModelCheckpoint
      init_args:
        monitor: val_negative_ELBO
        mode: min
    - class_path: EarlyStopping
      init_args:
        monitor: val_negative_ELBO
        mode: min
        patience: 3
data:
  data_dir: '/content/data'
  batch_size: 512
  num_workers: 1
model:
  learning_rate: 2e-05
  input_dim: 1
  latent_dim: 10