seed_everything: 23422
trainer:
  limit_predict_batches: 10
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: '.'
      name: 'logs/VAE_CIFARIO/inference_logs'
      default_hp_metric: False
  callbacks:
    - class_path: LogTestImageCallback
data:
  data_dir: '/content/data'
  batch_size: 1
  num_workers: 1
model:
  learning_rate: 9.6453e-05
  input_dim: 3
  latent_dim: 128
ckpt_path: null
