seed_everything: 42
trainer:
  limit_test_batches: 10
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: '.'
      name: 'logs/test_logs'
      default_hp_metric: False
  callbacks:
    - class_path: LogTestImageCallback
data:
  data_dir: '/content/data'
  batch_size: 1
  num_workers: 1
model:
  learning_rate: 8.317637711026709e-05
  output_dim: 128
ckpt_path: null